import {Dimensions, StyleSheet} from 'react-native';

const dartColor = '#40485A';
const lightColor = '#818792';
const mainRedColor = '#EB5757';

export const styles = StyleSheet.create({
  containerScanning: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#000',
    width: Dimensions.get('window').width,
    height: 200,
  },
  heading: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    position: 'absolute',
    justifyContent: 'center',
    top: 45,
  },
  goback: {
    position: 'absolute',
    left: 18,
  },
  heading_text: {
    fontSize: 18,
    color: 'white',
  },
  backButton: {
    width: 15,
    height: 25,
  },
  container: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  camera: {
    flex: 1,
    alignItems: 'center',
  },
  iconKeyboard: {
    marginHorizontal: 10,
    marginBottom: 1,
  },
  opacityTopView: {
    backgroundColor: 'rgba(10, 10, 10, 0.8)',
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '17%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  opacityLeftView: {
    backgroundColor: 'rgba(10, 10, 10, 0.8)',
    position: 'absolute',
    top: '17%',
    left: 0,
    width: 38,
    height: '35%',
  },
  opacityRightView: {
    backgroundColor: 'rgba(10, 10, 10, 0.8)',
    position: 'absolute',
    top: '17%',
    right: 0,
    width: 38,
    height: '35%',
  },
  opacityBottomView: {
    backgroundColor: 'rgba(10, 10, 10, 0.8)',
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    height: '48%',
    justifyContent: 'flex-start',
    paddingTop: '25%',
    alignItems: 'center',
  },
  infoView: {
    backgroundColor: 'white',
    position: 'absolute',
    top: '50%',
    width: Dimensions.get('screen').width - 76,
    paddingVertical: 5,
    left: 38,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  infoText: {
    fontSize: 14,
    fontWeight: '300',
    color: dartColor,
  },
  horizontalLine: {
    position: 'absolute',
    width: '100%',
    borderTopWidth: 0.8,
    borderColor: 'red',
    top: '35%',
  },
  bottomMessageBox: {
    flexDirection: 'row',
    width: '100%',
    position: 'absolute',
    bottom: 150,
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
  },
  manualText: {
    color: 'white',
    lineHeight: 19,
    fontSize: 14,
  },
  viewCartText: {
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 19,
  },
  continueText: {
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 19,
    color: 'white',
  },
  arrowBack: {
    width: 18,
    height: 18,
    borderLeftWidth: 3,
    borderBottomWidth: 3,
    borderColor: 'white',
    marginLeft: 10,
    transform: [{rotate: '45deg'}],
  },
  headerWrapped: {
    justifyContent: 'center',
    marginTop: 50,
    width: '100%',
    flexDirection: 'row',
    position: 'absolute',
    top: 0,
  },
  screenTitle: {
    color: 'white',
    fontSize: 18,
  },
  viewcartButton: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    width: 150,
    height: 60,
  },
  continueButton: {
    backgroundColor: '#80AF46',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    width: 150,
    height: 60,
    marginLeft: 30,
    flexDirection: 'row',
  },
  viewcartButtonWrapped: {
    position: 'absolute',
    width: '100%',
    justifyContent: 'center',
    bottom: 50,
    flexDirection: 'row',
  },
  guideText: {
    color: 'white',
    fontSize: 14,
    lineHeight: 19,
    marginTop: 30,
  },

  loadingView: {
    width: '95%',
    backgroundColor: 'white',
    paddingHorizontal: 9,
    paddingVertical: 26,
    borderRadius: 5,
  },

  // Product Item
  productItem: {
    width: '95%',
    backgroundColor: 'white',
    paddingHorizontal: 9,
    paddingVertical: 26,
    borderRadius: 5,
    flexDirection: 'row',
  },
  productImageWrapped: {
    width: 82,
    height: 87,
    position: 'relative',
  },
  productImage: {
    width: 80,
    height: 80,
    backgroundColor: '#eee',
    borderRadius: 2,
  },
  discountTag: {
    backgroundColor: mainRedColor,
    position: 'absolute',
    bottom: 0,
    left: 10,
    width: 63,
    height: 25,
    borderRadius: 3,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  discountTagText: {
    fontSize: 11,
    color: 'white',
    fontWeight: '700',
  },

  productTitle: {
    fontSize: 14,
    lineHeight: 16,
    color: dartColor,
  },
  lightText: {
    fontSize: 12,
    color: lightColor,
  },
  columnFlexEnd: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  finalPriceText: {
    color: mainRedColor,
    fontSize: 21,
    fontWeight: 'bold',
  },
  originalPriceText: {
    color: lightColor,
    textDecorationLine: 'line-through',
    fontSize: 12,
  },
  price: {
    color: lightColor,
    fontSize: 12,
  },
  discountPercentText: {
    color: mainRedColor,
    fontSize: 12,
    marginLeft: 5,
  },
  columnFullWidth: {
    flex: 1,
    flexDirection: 'column',
    marginLeft: 8,
  },
  manual_view: {
    flex: 1,
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  manual_header: {
    backgroundColor: 'white',
    width: '100%',
    height: 60,
    padding: 15,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  manual_header_text: {
    color: '#80AF46',
    fontSize: 21,
    fontWeight: '300',
  },
  input: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 14,
    fontWeight: '300',
    padding: 12,
  },
  error: {
    marginTop: 4,
    fontSize: 14,
    color: '#EB5757',
  },
  manual_content: {
    width: '100%',
    height: 145,
    backgroundColor: 'white',
    paddingLeft: 15,
    paddingRight: 15,
    paddingTop: 5,
  },
  inputContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#707070',
    borderRadius: 5.0,
    borderWidth: 1,
    borderStyle: 'solid',
  },
});
